name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Add outline to Markdown files
        run: |
          find pages -name "*.md" -exec sed -i '1i\---\noutline: deep\n---\n\n' {} \;

      - name: Add outline to Markdown files
        run: |
          find pages-fishtest -name "*.md" -exec sed -i '1i\---\noutline: deep\n---\n\n' {} \;

      - name: Add outline to Markdown files
        run: |
          find pages-nnue -name "*.md" -exec sed -i '1i\---\noutline: deep\n---\n\n' {} \;

      - name: Remove breaking fishtest files
        run: |
          rm -rf "pages-fishtest/A-developer's-guide-to-the-Stockfish-command-line.md"

      - run: npm ci
      - name: Build
        run: npm run docs:build
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .vitepress/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1